<?php
/***********************************************************************
File: config.inc
***********************************************************************/

$CONFIG = array(
  "author" => "Joachim Dürr",
  "description" => "Beispielprogramm HTML für VEM2021",
  "title" => "VEM2021 Chefkoch",
  "dsn" => "mysql:host=localhost;dbname=vem2021;charset=utf8",
  "username" => "vem2021",
  "password" => "vem"
);

?>